### ISSUE TITLE
Should we have sequence support?

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#130]
Here's a dump of the internal discussions about this one. We have to decide if we still need this after the 'uid' datatype,

Requirement:

    Keep sequence based ID's for various entities like web customer, subscription, etc.

 

Here's what I think a sequence boils down to:

    Named integer generator.
    Guarantee unique integer generated on each request.

 

Keep in mind that a single sequence could be used to populate values in more than one field/column.  So I'm keeping the "name" thing generic on purpose.  Our implementation might set the name to collection + attribute or entity + attribute.

 

One thing with MongoDB is to be careful with respect to shards.  Sequences have to be unique across all shards.  I don't know enough about this, but it seems that if we centralize sequence management, have it replicated across all datacenters, and require that it never be sharded we should be ok.  One downside there is the write performance when requesting a new block of numbers if the primary node in the replica set is not local to the requester.

 

There are several implementations listed on Create an Auto-Incrementing Sequence Field — MongoDB Manual 2.4.9.  But each would require storing a function.  It's possible to Store a JavaScript Function on the Server but according to that document it isn't recommended.  Also, I don't think this will work if we shard.

 

Another option is to have a document store current sequence values.  Applications can then request a set of values.  Maybe 100 at a time, or 10.. this is basically what oracle sequences do today in dolling out a chunk of numbers at a time.  The document would have to be stored in a collection that is not shared.  To make things easier to manage in the future I would recommend keeping all sequences in one dedicated collection.  How do we guarentee only one caller can request a chunk of numbers at a time?  I think we'll have to roll in some locking semantics.  Maybe when getting a block of numbers from the sequence first you have to generate a guid and save it on the collection.  Then you can get a block of numbers from the sequence if and only if your guid is the lock.  And if your guid isn't set, you have to wait until the lock is cleared or the lock expires.  Maybe something like this:

 

    {  
       "name": "user.webCustomerId",  
       "value": 98573835,  
       "lock": <guid>,  
       "lockTTL": "20140218 140000"  
    }  

-------------------------------------------------------------

Discussion on IRC about this today, wanted to dump it somewhere for posterity.

 

    14:14 < b> nmalik, looking at backlog, there is a US about sequence replacement. I am thinking we'd provide two ways of using it: an API call to

               inc and get the number, and some sort of syntax in insert and update to tell that the field will be initialized from a sequence. What

               do you think?

    14:19 <@nmalik> b: if the syntax for insert/update exists, why would we give the client the ability to set something themselves?  I'm a fan of

                    having a sequence type in metadata that will auto-assign a value on insert (or creation of a sub-document in the case of

                    update/set).

    14:29 < b> nmalik, what do you mean by syntax for insert/update exists?

    14:31 <@nmalik> b: sorry, if there's some way to specify in metadata that a sequence is used to populate a field on creation of that object

    14:31 < b> nmalik, we can add that as a constraint on a field

    14:32 < b> nmalik, and generate and set if field is null

    14:32 < b> nmalik, do we ever have a case where someone needs to get the next from a sequence manually?

    14:32 <@nmalik> b: if that is set on a field why would the client be able to set it on creation of the object?  there's a risk of collision

    14:33 <@nmalik> b: only case I can think of is a bit of a hacky thing in ebs inbound order processing.  the pl/sql sets the id on the order line

                    manually instead of letting the proc do it. 

    14:33 <@nmalik> summary: no

    14:35 < b> so in summary: new field level constraint that says "set from sequence (seq name given)". Then, we'll set the field on insert/update

               if it is null. Should we allow clients to set the field if they don't want to use the sequence? I'd say yes, but that's debatable

    14:36 < b> forcing the clients to pass that as null seems a bit restrictive to me

    14:36 <@nmalik> I vote no, else will have to do collision handling.  if current sequence is 1 and client sets a value of 2, in a few inserts

                    without the client setting a number it will fail unless sequence is advanced until a valid number is found

    14:37 < b> true, and I'd say that's caller's problem

    14:37 <@nmalik> yes, but only if we allow it to be a problem

    14:37 <@nmalik> what's the value in the caller setting a sequence managed field manually?

    14:39 < b> I can't think of a concrete example

    14:40 <@nmalik> only time it might be useful, as it is with that ebs order thing, is when the id has to be referenced by something else

    14:40 < b> one mongo constraint: the collection containing the sequences should not be replicated.

    14:42 < b> lets do it the way you say, and think about it when we find a problem with it

    14:43 <@nmalik> you mean not sharded?

    14:44 < b> the way that I read docs, sharding won't have any affect on the operation

    14:44 < b> but replication would

    14:44 < b> because clients may read old copy from a replica

    14:45 <@nmalik> can we force a collection to be read only from the primary?

    14:45 < b> but the only operation on a sequence document will be an atomic read-and-update

    14:45 < b> yes, we can

    14:45 <@nmalik> right, so with read-and-update it will always hit the primary

    14:45 < b> and, depending on how read-update is implemented, we might be ok with replication

    14:46 <@nmalik> since it's atomic the lock has to happen where the update is executed, which is the primary

    14:46 < b> that's what I'd guess

    14:46 <@nmalik> yea, I'm guessing too, but makes sense that way

    14:46 < b> there is an update api that returns the old version of the doc, so that's the one we'd use to update

    14:47 < b> one doc per sequence, containing sequence name and value

    14:48 < b> always increment by 1

    14:48 <@nmalik> what about batch insert? could increment by the batch size, return the first number in the set

    14:49 < b> that's something we can't do with a metadata based approach

    14:49 < b> could be done via an api

    14:50 < b> hmm, maybe

    14:50 < b> the doc inserter/updater can pre-process the docs, and allocate sequences at once

    14:51 <@nmalik> I assume it'd be worth the pre-processing, especially if sequences can be set on objects in an array

    14:51 < b> yes

     

 

Summary:

    Have a separate sequence collection.
    Client will not have access to the sequence collection.
        Revisit later if new requirements are found.
    A sequence is represented by a document.
    Update and read of sequence must be atomic, using read-and-update
        If a read happens on a non-primary it's possible it will get stale data?
    Update metadata to support a new data type for sequences.  Set the name of the sequence as well, new field.
    Pre-processor can allocate values for each sequences once per batch (reducing requests to database).

-------------------------------

One way is to use indexes: add a unique index for the field that is to be generated from the sequence, and manually compute the max, insert with max+1, and keep incrementing and retrying until it is saved. Requires that the service deals with the generation of the number.

 

Another option is to keep a collection with one document for every generated id, and use the _id field. It is hex, so we can convert it back to an integer. Waste of space, but we can keep object information in the doc, and it becomes a somewhat useless "index of everything".

 

That said, iirc the only situation where we use a sequence manually to generate a number is subscription number. For all other cases, _id should work. Or, am I wrong in that assumption?

--------------------------------------------

...

As for creating a new document with an ID, do we have to actually create a document?  The _id default is internally an object ObjectId.  Can we generate one on the fly?  Basically it's a GUID, so any other such generation could be an option if it's a try til you succeed process.  Was looking for javadoc on GUID class when I found http://cowtowncoder.github.io/java-uuid-generator/javadoc/3.1.3/com/fasterxml/uuid/package-summary.html. 

----------------------------------------------
Do those have to be sequence based? Can we use GUIDs for those (strings)? Or, large numbers, because that's what we're going to get if we convert a GUID to decimal.

 

The benefit of an actual document is that we can have a true sequence-like behavior (monotonically increasing ints with minimal gaps)

----------------------------

No requirement for them to be sequential.  Easiest to make them large numbers, else will have to look at what code uses it and make sure it can handle the cases when it's a string.

**Comment by jewzaam** [comment]
Does this go away with #204?

**Comment by bserdar** [comment]
I guess we can include sequence generation in #204.
