### ISSUE TITLE
Analysis of possible failures

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-core#169]
Hi guys,

I saw this paper ( https://www.usenix.org/conference/osdi14/technical-sessions/presentation/yuan )  (which the open source project is https://github.com/diy1/aspirator ) which shows that some static analysis could solve failures before they happen. I would consider run on the lightblue projects/modules  and also review the sonar issues in nemo (for example for core  http://nemo.sonarqube.org/dashboard/index/717402 )

**Comment by jewzaam** [comment]
@luan-cestari is there any action you'd like taken for this issue?  Right now I just see it as some links to papers to read, which may be useful but given you read them could you provide some tangible things we could do improve analysis processes?

**Comment by luan-cestari** [comment]
@jewzaam Sorry, I didn't have time until now to do that (as I had other priorities, so I left the links that could provides the introduction of how to test and generate the issues for someone that could take this issue). I will take a look on this after I finish the PR about sonar repositories, ok?

**Comment by luan-cestari** [comment]
# Aspirator (jchord + its own plugin) vs Sonar (Sonar plugins) - The Big Picture 

This text will explore how to briefly compare these two tools so we could decide how deep we would like to go with the usage of the new tool (aspirator/jchord) , for example, if we would want to include that in our quality process if it shows to have a advantages over the Sonar. In case of questions, we can enhance this text after new conclusions and findings of the discussion. Hope that the referenced material also support our decision and helps to avoid much further explanations (details and etc). Most of the context below will mention the Aspirator project and related as it have few documentation, which made necessary to us to create this to understand it better.

### Aspirator

 Aspirator (https://github.com/diy1/aspirator) is a tool made by some researchers from University of Toronto last year which can generate a set of dynamic and static code analysis. This project is based on the Chord/JChord project (which this one was made by Stanford and Intel Research Berkeley and started in 2008) (https://code.google.com/p/jchord/) that is the analysis engine (both static and dynamic analyser) that also come with some built-in analysis. The Aspirator also added some new options to Chord to process more complex projects.

Below a quote from the https://github.com/diy1/aspirator about it new analysis over the Chord:

> - exception-empty-handler-java: detecting empty exception handler
> - terminating-handler-java: detecting unexpected abort in exception overcatch
> - exception-todo-in-handler-java: detecting "TODO" and "FIXME" in exception handler

Also, it (https://github.com/diy1/aspirator) mentions:

> Aspirator is a tool that checks for trivial bug patterns in exception handlers for Java or JVM compatible programs. .... These trivial bugs in exception handlers have been shown to have caused a significant number of deadly failures for distributed systems.

Using this simple rules made by themselves and using some open source code to be analyzed (from projects like Hadoop and Cassandra) , aspirator found 121 bugs (85 confirmed by the projects owners) and 379 bad practice (which 58 were confirmed) (more details on the paper https://www.usenix.org/system/files/conference/osdi14/osdi14-paper-yuan.pdf , the presentation made of this paper on https://www.usenix.org/conference/osdi14/technical-sessions/presentation/yuan and the results with links to the issues on http://www.eecg.toronto.edu/failureAnalysis/ )

Like Aspirator, other projects with papers have explored the analyses capability to find other problems of Java code (or made using other languages that rely on bytecode) (http://www.eecs.berkeley.edu/Pubs/TechRpts/2012/EECS-2012-67.pdf).

As already mentioned Chord have other built analysis but as some papers and other places already mentioned, there are things undocumented from this project, including configuration. Using ```fgrep``` command over the Aspirator source code (using the ```fgrep @Chord * -lr | xargs fgrep -l 'java"' | fgrep -v .tex | fgrep -v .txt | sort | uniq ```) . we can find the following possible analysis (which will include some new classes from Aspirator): 

 - chord-src-2.1/src/chord/analyses/alias/CICG2DotGraphAnalysis.java
 - chord-src-2.1/src/chord/analyses/alias/CICGAnalysis.java
 - chord-src-2.1/src/chord/analyses/alias/CIPAAnalysis.java
 - chord-src-2.1/src/chord/analyses/alias/CSCGAnalysis.java
 - chord-src-2.1/src/chord/analyses/alias/CSPAAnalysis.java
 - chord-src-2.1/src/chord/analyses/alias/CtxtsAnalysis.java
 - chord-src-2.1/src/chord/analyses/datarace/DataraceAnalysis.java
 - chord-src-2.1/src/chord/analyses/deadlock/DeadlockAnalysis.java
 - chord-src-2.1/src/chord/analyses/dynamic/DynamicHeapAnalysis.java
 - chord-src-2.1/src/chord/analyses/escape/dynamic/DynamicThreadEscapeAnalysis.java
 - chord-src-2.1/src/chord/analyses/escape/hybrid/full/ThreadEscapeFullAnalysis.java
 - chord-src-2.1/src/chord/analyses/escape/hybrid/path/ThreadEscapePathAnalysis.java
 - chord-src-2.1/src/chord/analyses/exceptionHandlerBugs/CheckEmptyHandler.java
 - chord-src-2.1/src/chord/analyses/exceptionHandlerBugs/CheckTerminatingHandler.java
 - chord-src-2.1/src/chord/analyses/exceptionHandlerBugs/CheckUnhandledExceptions.java
 - chord-src-2.1/src/chord/analyses/exceptionHandlerBugs/TestException.java
 - chord-src-2.1/src/chord/analyses/exceptionHandlerBugs/TODOinHandler.java
 - chord-src-2.1/src/chord/analyses/inst/PhiInstAnalysis.java
 - chord-src-2.1/src/chord/analyses/reflect/ConNewInstAnalysis.java
 - chord-src-2.1/src/chord/analyses/reflect/ObjNewInstAnalysis.java
 - chord-src-2.1/src/chord/analyses/testCFG/TestCFG.java
 - chord-src-2.1/src/chord/analyses/testDFlow/.TestCFG.java.swp
 - chord-src-2.1/src/chord/analyses/testDFlow/TestDFlow.java
 - chord-src-2.1/src/chord/analyses/thread/ThreadAnalysis.java
 - chord-src-2.1/src/chord/analyses/thread/ThrSenCICGAnalysis.java
 - chord-src-2.1/src/chord/analyses/typestate/TypeStateAnalysis.java

In the brief time that I had to take a look over the source code and thanks to the http://pag.gatech.edu/chord.html , there are the following analysis: various may-alias and call-graph analyses, thread-escape analysis, static and dynamic concurrency analyses for finding races, deadlocks, atomicity violations and others.

JChord provides a good documentation and example of how to use its framework for building new types of analyses (like Aspirator and others did).

One problem that might be faced to use JChord is that it has an easily ant integration (or you would need to run using the command line) and as our project is based on maven, the port is bit trick. We could solve this by:
 - creating a ant build.xml file just for tests;
 - or using maven-ant plugin (https://maven.apache.org/plugins/maven-antrun-plugin/);
 - or creating a docker image prepared to process an project (https://www.docker.com/);
 - or a maven plugin (https://maven.apache.org/guides/plugin/guide-java-plugin-development.html)
 - or create a sonar plugin (http://docs.sonarqube.org/display/SONAR/Hosting+on+the+Forge   https://deors.wordpress.com/2014/03/20/sonarqube-plugins-1/ )
 - or even just use on a single machine already prepared once to see the results.

As Chrod generate some native shared libraries with java interface for instrumentation (.so .ddl), to build from scratch you have to install the native c/c++ dev kit in your machine and its dependencies (not found an specific part of documentation describing this better and I already have many different tools already installed and configured) .

For more question about Chord, there is a google-groups forum https://groups.google.com/forum/#!forum/chord-discuss .

### Sonar

The sonar has plugin-based architecture which you can add different tools (such as https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#Java) to enhance it analysis capabilities, including new languages. In our case (http://sonar.lightblue.io/profiles) we use a specific profile ( http://sonar.lightblue.io/rules_configuration/index/3 ) with 404 rules absed on different plugins (most findbugs) (more info about the sonar plugins http://docs.sonarqube.org/display/SONAR/Java+Plugin  http://docs.sonarqube.org/display/SONAR/Java-specific+Plugins) . 

Due the Sonar nature, it would be complex to evaluate each plugin made, as the most of rules seems to be from findbug, let consider this one for our comparison as it is a static analysis tool (https://code.google.com/p/findbugs/  http://www.ibm.com/developerworks/library/j-findbug2/ ).

### Comparison & Future Work. & Conclusions

The comparison might be quite hard to be very tangible as there is as many rules on Aspirator as in Findbugs (http://findbugs.sourceforge.net/bugDescriptions.html) (or other Sonar compatible tools) and also, Sonar have an huge set of rules and it is hard to find or to be sure if the rules on Aspirator have complety identical behavior.

To something more concrete, we have to decide if we will go further on the Aspirator and how we plan to do, as we can see its results and also he have to keep in mind that even if don't get any issues now, it doesn't mean that it doesn't work or it is invalid or that it works like the sonar (suppose that it also doesn't get any issue related) but as our code change maybe an issue will rise that only this tool could find it (if it is likely to happen or not is up to us to decise).

**Comment by jewzaam** [comment]
Given there isn't a clear comparison between what we have in place (Sonar) and the new tool (Aspirator) I feel it's a tough call to spend time on something new.  I do like the idea of a sonar plugin.  This makes me wonder if there are other sonar plugins we could use that could give us some value easier.  Having it all in sonar provides a single tool for reviewing status, which is very nice.

From previous conversations with @luan-cestari it doesn't seem Aspirator is very mature, lacking good documentation on what rules are out there is an example.  Having to infer what can be tested by grepping code is a bit fun.  A challenge with this type of thing is how it is maintained.  Is it something we can reasonably expect to be updated periodically or is it going to remain fairly static?

If anything is done, I think looking at those existing sonar plugins would be a better use of time.

**Comment by luan-cestari** [comment]
I think there other sonar plugins (http://docs.sonarqube.org/display/SONAR/Java-specific+Plugins) that we could use (maybe instead of aspirator).  I saw the default rules used by us are just from to different providers,which two rules are from the Sonar itself (http://sonar.lightblue.io/rules_configuration/index/3?sort_by=SORT_BY_RULE_NAME&searchtext=&repositories%5B%5D=squid&rule_activation=ACTIVE&commit=Search) and the remaning are from Findbugs (http://sonar.lightblue.io/rules_configuration/index/3?sort_by=SORT_BY_RULE_NAME&searchtext=&repositories%5B%5D=findbugs&rule_activation=ACTIVE&commit=Search) . In the Findbugs I noticed that there were few changes in the repository (last change was just updateing sonar api changes, but some changes are older than one year) and I also found the file descriptor for sonar know the rules (https://github.com/SonarSource/sonar-findbugs/blob/master/src/main/resources/com/sonar/sqale/findbugs-model.xml) . Looking these rules and the PMD rules as well (https://github.com/SonarCommunity/sonar-pmd/blob/master/src/main/resources/com/sonar/sqale/pmd-model.xml) I saw that both have some rules for problems with the usage of "exceptions".  I would consider install PMD plugin (http://docs.sonarqube.org/display/SONAR/PMD+Plugin) to see if it have new important issues. There is another static code analysis tools that I would also consider to install. One of them is Atlassian Clover (http://docs.sonarqube.org/display/SONAR/Clover+Plugin) (the problem is that it needs an license but it seems that Red Hat have already)  and maybe build a sonar plugin for the intellij inspection tool ( https://www.jetbrains.com/idea/help/running-inspections-offline.html#d1544853e119 more than 600 rules https://www.jetbrains.com/idea/documentation/inspections.jsp  the source https://github.com/JetBrains/intellij-community/tree/master/plugins/InspectionGadgets ).

Maybe Checkstyle (http://docs.sonarqube.org/display/SONAR/Checkstyle+Plugin   http://checkstyle.sourceforge.net/ ) could also help (there are some rules for "exception" for example) (I remeember reading and article/paper about how the google checkstyle https://google-styleguide.googlecode.com/svn/trunk/javaguide.html helped to prevent many bugs once).

There are other two interesting Sonar plugins that not related to this topic but might be nice to have (http://docs.codehaus.org/display/SONAR/Build+Stability+Plugin    http://docs.sonarqube.org/display/SONAR/Clirr+Plugin)

One thing we should keep eye on is any update from sonar (any any third party plugin installed) (maybe checking mostly a new release or maybe the PRs in their github repositories if we want to use snapshots ,like the default java plugins repo https://github.com/SonarSource/sonar-java/pulls ) . We could reevaluate the rules disabled in the profile we uploaded in sonar, maybe some rules disabled are new rules that didn't exist previously or even some rules make sense for lightblue. 

About Aspirator, well, I think that it would be quite hard that none of the plugins got anything related, probably what happened is the teams usually have already some known bugs and enhances on the back log and doesn't check very often Sonar or other static analysis tool. But we could make the plugin if we want, I don't think either the Aspirator and Chord will change (major, minor or even patches) as they are more like research material, so it would only be used from time to time and probably the next group of researches would create another extension from that source code

**Comment by luan-cestari** [comment]
Maybe we could also get some nice rules from other public sonar for open source projects like the pache one https://analysis.apache.org/profiles .

**Comment by jewzaam** [comment]
@luan-cestari given the many recommendations above I'd say we should break these things into separate issues for implementation.  Another aspect you touched on is staying up to date.  I see that as a separate issue and something we should do.  But maybe less important that looking at using some other plugins.  I like the idea of the checkstyle, but we don't enforce the [style guideline](http://dev.docs.lightblue.io/formatting/README.html) we have.

**Comment by luan-cestari** [comment]
@jewzaam . I just created all the issues for each consumable task discussed [*].

About the checkstyle, I agree with our guideline but using the checkstyle plugin doesn't mean to reject any code due its format. Put it in another way (like I saw in apache's sonar instance) we can active the set of rules that we think it is relevant (like avoid the System.out.println usage) and thiese rules would just help to find issues, no code would be rejected due the sonar rule (so we would accept code that is using the System.out.println but we can fix it later when we think it would be necessary, for example). 

Do you think we should close this issue now? 


*:
https://github.com/lightblue-platform/lightblue-core/issues/319
https://github.com/lightblue-platform/lightblue-core/issues/320
https://github.com/lightblue-platform/lightblue-core/issues/321
https://github.com/lightblue-platform/lightblue-core/issues/322
https://github.com/lightblue-platform/lightblue-core/issues/323
https://github.com/lightblue-platform/lightblue-core/issues/324
https://github.com/lightblue-platform/lightblue-core/issues/325
https://github.com/lightblue-platform/lightblue-core/issues/326
https://github.com/lightblue-platform/lightblue-core/issues/327

**Comment by jewzaam** [comment]
Yes, closing it. Thanks.
