### ISSUE TITLE
It should be possible to update arrays with objects

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#180]
The below update expression is not supported. Append only takes empty objects, or values, not initialized objects. The problem here is the inability to access metadata for the fields in the initialized object.

{
            "$foreach": {
                "termsVerbiage": {
                    "field": "uid",
                    "op": "=",
                    "rvalue": "338e5c42-eaff-42b1-8ba2-391b4aab166d"
                },
                "$update": {
                    "$append": {
                        "termsVerbiageTranslation": {
                            "localeCode": "lg",
                            "localeText": "Language",
                            "statusCode": "active",
                            "version": "1"
                        }
                    }
                }
            }
        }

**Comment by jewzaam** [comment]
@bserdar this is assigned to you, any work been done on it?  Should it be moved back to "ready"?

**Comment by bserdar** [comment]
No work has been done. Lets move it back to ready.
