### ISSUE TITLE
Fill the COPYING template gaps

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-core#190]
The COPYING file have some template marks which seems that change (for example, to specify the year and the name of the program, etc). This should be also verified in the other repositories. Another point related to this is by default Github create a file named LICENSE for this, would be the case to us rename our file?

**Comment by luan-cestari** [comment]
If the PR is approved, the same file will be copied to the other repositories:
https://github.com/lightblue-platform/lightblue-ldap/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-puppet/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-applications/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-rest/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-docs-user
https://github.com/lightblue-platform/lightblue-migrator
https://github.com/lightblue-platform/lightblue/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-mongo/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-rdbms/blob/master/COPYING
https://github.com/lightblue-platform/openshift-lightblue-cart/blob/master/LICENSE
https://github.com/lightblue-platform/lightblue-docs-overview
https://github.com/lightblue-platform/lightblue-docs-developer
https://github.com/lightblue-platform/lightblue-client/blob/master/LICENSE
https://github.com/lightblue-platform/lightblue-dockerfiles/blob/master/COPYING
https://github.com/lightblue-platform/lightblue-tests/blob/master/LICENSE
https://github.com/lightblue-platform/openshift-lightblue-all/blob/master/LICENSE
https://github.com/lightblue-platform/lightblue-audit-hook/blob/master/LICENSE
https://github.com/lightblue-platform/shakespeares-monkey/blob/master/COPYING
https://github.com/lightblue-platform/turbine-rpm/blob/master/LICENSE

**Comment by jewzaam** [comment]
The author could (should?) be changed from "Red Hat" to "lightblue Contributors".  This came up in a call with internal OSEP (open source enablment community of practice) including representation from legal.  Really this isn't by Red Hat, it's whoever is contributing to lightblue.  We're happy to have some external contributions and hope for more.

**Comment by luan-cestari** [comment]
Changed. Is it correct now? https://github.com/lightblue-platform/lightblue-core/pull/271/files 
May I also change the other projects' files?

**Comment by jewzaam** [comment]
+1

**Comment by luan-cestari** [comment]
PR created so far (github stopped me to created all as I submitted too quickly after a previous PRs)
https://github.com/lightblue-platform/turbine-rpm/pull/3
https://github.com/lightblue-platform/shakespeares-monkey/pull/4
https://github.com/lightblue-platform/lightblue-audit-hook/pull/20
https://github.com/lightblue-platform/openshift-lightblue-all/pull/6
https://github.com/lightblue-platform/lightblue-tests/pull/9
https://github.com/lightblue-platform/lightblue-dockerfiles/pull/5
https://github.com/lightblue-platform/lightblue-client/pull/44
https://github.com/lightblue-platform/lightblue-docs-developer/pull/16

**Comment by luan-cestari** [comment]
Maybe we could add to all readme.md (it was only on a single outdated file,) (I think it would be another issue, not this one)
Overview of how migrations are happening from legacy systems to lightblue:
 * [lightblue Migrations](http://www.slideshare.net/derek63/lightblue-migration)

**Comment by luan-cestari** [comment]
Other PRs
https://github.com/lightblue-platform/lightblue-docs-overview/pull/8
https://github.com/lightblue-platform/openshift-lightblue-cart/pull/8
https://github.com/lightblue-platform/lightblue-rdbms/pull/89
https://github.com/lightblue-platform/lightblue-mongo/pull/49
https://github.com/lightblue-platform/lightblue/pull/14
https://github.com/lightblue-platform/lightblue-migrator/pull/52
https://github.com/lightblue-platform/lightblue-core/pull/273
https://github.com/lightblue-platform/lightblue-puppet/pull/48
https://github.com/lightblue-platform/lightblue-ldap/pull/5
https://github.com/lightblue-platform/lightblue-applications/pull/44
https://github.com/lightblue-platform/lightblue-rest/pull/63
https://github.com/lightblue-platform/lightblue-docs-user/pull/59

Let me know if I forgot any PR or project that we own.

**Comment by luan-cestari** [comment]
I think just the PR https://github.com/lightblue-platform/openshift-lightblue-all/pull/6 is pending now. Also, I thought it would be useful to reference the new discussion we just started in nabble http://dev.forum.lightblue.io/Repo-README-md-files-td276.html

**Comment by jewzaam** [comment]
All referenced PR's are merged.  Closing.
