### ISSUE TITLE
Create 2 new roles for metadata

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-core#199]
Create any and none roles for metadata. More details discussed in https://github.com/lightblue-platform/lightblue-core/pull/187 and https://github.com/lightblue-platform/lightblue-rest/issues/1

**Comment by dcrissman** [comment]
After chatting with @derek63, I will add the any/none roles in this issue, then spin off another story in the puppet module to land the permissions in the config file.

**Comment by luan-cestari** [comment]
It closed due it was mentioned in the PR https://github.com/lightblue-platform/lightblue-core/pull/270 .  It also needs this PR https://github.com/lightblue-platform/lightblue-rest/pull/61  (not merged yet due build failure )
