### ISSUE TITLE
Add 'generated' constraint to metadata

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#204]
And will ripple into mongo (maybe rdbms).  Basically for any required (or identity) field we need a way to indicate that the backend will handle creation of that field if it isn't set already.

Specific use case is for _id field in mongo.  It's automatically added as 'identity' right now and a value is always assigned before a document is created by the mongo crud controller.  The change should mean the _id field is not generated by lightblue code, but instead handled by the backend.

Question: should this distinguish between the case when the backend will always generate a value vs will generate only if not set by caller?

**Comment by paterczm** [comment]
The 'generated' constraint should allow setting the type of generated data, i.e. you may want to generate numeric IDs, rather than hashes. Numeric IDs can be essential when migrating to lightblue from rdbms. For more information, see https://mojo.redhat.com/message/957922#957922.

Does the ready label mean it's done?

**Comment by jewzaam** [comment]
"ready" means it can be pulled to "in progress"
see https://waffle.io/lightblue-platform/lightblue

**Comment by bserdar** [comment]
How about creating constraints for different types of generation strategies. There can be a sequence generator, and a uid generator, etc.

**Comment by jewzaam** [comment]
@bserdar a design doc will be added in the lightblue repo early next week, so we'll see what Marek has in mind soon.

**Comment by jewzaam** [comment]
See https://github.com/lightblue-platform/lightblue/pull/22

**Comment by jewzaam** [comment]
Related to #152

**Comment by jewzaam** [comment]
Add capability to do default (static) values when not specified by the client.  Replaces #152

**Comment by bserdar** [comment]
This should come with a disclaimer: even if there is a default for a field,
the field can still be null or unspecified in some documents, because when
we add a default, we will not update all the existing document.

**Comment by jewzaam** [comment]
Also need to account for when the field gets generated.  List of operations that can be [ insert, update, save ] and default if not specified is "insert"?

**Comment by paterczm** [comment]
> List of operations that can be [ insert, update, save ] and default if not specified is "insert"?

Do you see a use case for this? Generating on insert, when client did not specify a value for the generated field, covers pretty much all the needs I can think of.

**Comment by bserdar** [comment]
It also needs to be done on update/save, if the generated field is a member
of a container object (nested object or array), and the container object
was null before, and not null after update.

So, I don't think it is necessary to specify a list of operations.

**Comment by beachw08** [comment]
AMS would like the ability to generate numeric Id's for our tnc phase2 project. If we can't generate numeric id's then we will break terms service if we go to production with our code.

**Comment by bsaylor1** [comment]
@jewzaam ,
Will this be fixed before Mid-September, 2015?

That is our expected delivery date for Terms N Conditions and i'm told, this issue will certainly impact that delivery date if it's not fixed.

**Comment by jewzaam** [comment]
@paterczm any update on status?  It's marked in progress and owned by you.  I suspect that isn't really true anymore..

**Comment by paterczm** [comment]
@jewzaam, yes, I'm not working on it. The design discussion has not come to a conclusion and priority dropped, because it was identified as not needed for the initial release.

**Comment by bsaylor1** [comment]
@jewzaam , How can we increase priority of this item?

At this point impact of not getting this done soon would delay a Project for bring delivered on time. Please see comment from myself and @beachw08 above for more details.

Thanks for your guys help on this.

**Comment by paterczm** [comment]
And here is the discussion: https://github.com/lightblue-platform/lightblue/pull/22

**Comment by jewzaam** [comment]
Can this be closed now?

**Comment by bserdar** [comment]
I think this can be closed now.
