### ISSUE TITLE
RelativeRewriteIterator should rewrite paths with $this and $parent

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#220]
I will have a PR with an ignored test in a bit in the renamed `RelativeRewriteIteratorTest` class that shows an example where a path should be rewritten remove `$parent`.  Should it also strip out `$this` where it isnt' necessary?  Seems an opportunity to simplify the paths, but for this it may not be worth the effort.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/pull/608

Query rewriting is rewritten in that PR, and should work as expected
