### ISSUE TITLE
Composite metadata array projection should be applied to the query

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#266]
You can use [array projection](http://docs.lightblue.io/language_specification/query.html#projection) to limit the results from an array field.  In the case of non-root metadata as a part of composite metadata this could be added to the query used instead of applied in memory after retrieving from the backend.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/pull/608

**Comment by bserdar** [comment]
Fixed in v2.
