### ISSUE TITLE
rdbms section of schema not being persisted

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-core#282]
When creating a new entity with rdbms information provided in the schema, or when updating an the schema section of an entity's metadata. No error is reported, it is just not saved.  The absence of this causes a runtime error when accessing an RDBMS entity

**Comment by bserdar** [comment]
The problem is larger. There is no way to register parser extensions. Some
refactoring to the config module is needed.

**Comment by bserdar** [comment]
Here's what I propose:

1) Create a new interface, BackendDescriptor. This interface will return
the CRUDController for the back end, and the DataStoreParser
2) lightblue-crud config file will have a list of backends.
3) datasources.json will *not* have a datastoreparser element or type
element. Instead, It'll have a "backend" element
4) lightblue-metadata config file will not have a "type" element, instead
it'll have a "backend" element
5) BackendDescriptor will provide metadata related functionality.
6) BackendDescriptor implementations will have a chance to configure
metadata classes. This way, RDBMS will be able to add its hooks to wherever
necessary.

Thoughts?

**Comment by jewzaam** [comment]
datasources.json is just for the mongo datasources.  Is there a need to change it for this?

----- Original Message -----
> Here's what I propose:
> 
> 1) Create a new interface, BackendDescriptor. This interface will return
> the CRUDController for the back end, and the DataStoreParser
> 2) lightblue-crud config file will have a list of backends.
> 3) datasources.json will *not* have a datastoreparser element or type
> element. Instead, It'll have a "backend" element
> 4) lightblue-metadata config file will not have a "type" element, instead
> it'll have a "backend" element
> 5) BackendDescriptor will provide metadata related functionality.
> 6) BackendDescriptor implementations will have a chance to configure
> metadata classes. This way, RDBMS will be able to add its hooks to wherever
> necessary.
> 
> Thoughts?
>

**Comment by bserdar** [comment]
It is not meant to be only for mongo datasources. RDBMS datasource info can
be put there as well, but we're not using it that way.

**Comment by jewzaam** [comment]
True, but it exists because the container didn't have away to do mongo datasource management.  It can do RDBMS just fine.  But, we can keep it generic.

----- Original Message -----

**Comment by derek63** [comment]
The current implementation of rdbms does is using datasources.json that way.  I had to add the following config for rdbms metadata parsing happen without failure.

"rdbms" : {
        "type" : "com.redhat.lightblue.config.rdbms.RDBMSDataSourceConfiguration",
        "metadataDataStoreParser" : "com.redhat.lightblue.metadata.rdbms.impl.RDBMSDataStoreParser",
 
        "database" : "myDB",
        "connections":[
            {
                "datasourceName": "myDS",
                "JNDI": "java:/myDB/myDS"
            }
        ]
 
    }
