### ISSUE TITLE
enhance nary_comparison to support referencing a field instead of a static list of values

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#283]
A problem for many-to-many associations. Cannot do today without having a separate entity that makes it a 1:m and m:1 (one entity too much if you ask me).

**Comment by bserdar** [comment]
I think we can evaluate this efficiently for associations. For mongodb,
this'll write a javascript query.

**Comment by bserdar** [comment]
For syntax, I think the best will be FieldComparisonExpression:

{ 'field': <field1>, 'op':'=','rfield':<field2> }

where field1 or field2 is an array of simple values.

**Comment by jewzaam** [comment]
Makes sense, that's what I was looking at first in the spec to see if we had that support.

----- Original Message -----
> For syntax, I think the best will be FieldComparisonExpression:
> 
> { 'field': <field1>, 'op':'=','rfield':<field2> }
> 
> where field1 or field2 is an array of simple values.
>

**Comment by bserdar** [comment]
What would you expect from an expression

  { "field":"field1","op":"<","rfield":"field2" }

where field1 and field2 are both arrays?

One way of doing it is to treat arrays like sets, and evaluate this as
   "evaluates to true if field1[i] < field2[j] for all i,j"
This has problems with evaluating "=". No two arrays would be equal if they
have more than one element.

Another way is:

   "evaluates to true if field1[i] op field2[i] for all i"

Comparing a value with a non-existant index needs to be defined.

I am leaning towards the second interpretation.

Thoughts?

**Comment by jewzaam** [comment]
The second interpretation is reasonable to me.  The main driver for this issue I think is the ability to check if the value of a simple field is in an array:

{ "field":"simpleField","op":"$in","rfield":"arrayField" }

**Comment by jblashka** [comment]
If we're going with the second interpretation, how would this work for two arrays using the $in/$nin operators? To me, it would mean that the field1 array would be a subset of the field2 array i.e. each value in field1 is also contained in field 2.

**Comment by bserdar** [comment]
I got this one wrong. I was going with the assumption that field comparison
expression needs to be changed, because that's what we deal with in
associations. I think that's not useful, so I'll throw that away.

Restarting: it should be something like:

{ "field': someField, "op":"$in", :values":arrayField }

This one doesn't accept arrayField for "field", so simpler semantics can be
implemented.

The problem will be evaluating this in associations. This will complicate
variable binding logic.

**Comment by luan-cestari** [comment]
Commented https://github.com/lightblue-platform/lightblue-core/pull/297
