### ISSUE TITLE
Need way to specifically refer to foreign fields from queries inside an association

### ISSUE THREAD

**Issue by jblashka** [lightblue-platform/lightblue-core#287]
Some fields in entity A:

      "x": {
        "type": "array",
        "items": {
          "type": "object",
          "fields": {
            "y" : {
              "constraints" : {
                "required" : true
              },
              "type" : "string"
            },
            "z" : {
              "constraints" : {
                "required" : true
              },
              "type" : "string"
            }
          }
        }
      },
      "xref": {
        "type": "reference",
        "entity": "B",
        "versionValue": "1.0.1-SNAPSHOT",
        "query": {
            "array": "$parent.x",
            "elemMatch": { "$and" : [
                {
                    "field": "y",
                    "op": "=",
                    "rfield": "y"
                },
                {
                    "field": "z",
                    "op": "=",
                    "rfield": "z"
                }
            ]}
        },
        "projection" : { "field":"*","include":true,"recursive":true },
        "sort": [ { "y":"$asc" }, { "z" : "$asc" } ]
      },

Some fields from entity B:

      "y" : {
        "constraints" : {
          "required" : true
        },
        "type" : "string"
      },
      "z" : {
        "constraints" : {
          "required" : true
        },
        "type" : "string"
      },

The problem:
The namespace gets changed when using an elemMatch. Inside the elemMatch in the reference, `"field" : "y"` is supposed to be the y field from the array of objects in entity A ($parent.y would be referring to something on the same level as x, right?) BUT I want `"rfield" : "y"` to be the y field from entity B (because with associations there's no prefix to refer to fields from the referenced entity). Now both field references are the same and I don't know what's going to happen. If I could do something explicit to reference the other entity (i.e. `"rfield" : "$other.y"`) I think it would become more clear what fields are coming from where.

**Comment by bserdar** [comment]
if field is supposed to point to A.y, and rfield is supposed to point to
B.y:

  "field":"y"
  "rfield":"$parent.xref.y"

should work. Since the namespace is "A.x" for elemMatch, you can derive
relative paths for fields anywhere in the tree.
