### ISSUE TITLE
Simplify extension persistence, save as string?

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#291]
Instead of having each backend save its configuration just save things as strings.  Meaning, backend specific configurations, which have placeholders in the core metadata, just get saved as the json string instead of bson object structures.  This is already being done for association query, projection, and sort.  Seems it would make extending lightblue (adding new controllers) just a little bit easier.  The controller still has to parse it but that's it.

**Comment by jewzaam** [comment]
Will have to deal with fixing existing data.

**Comment by bserdar** [comment]
This is probably no longer relevant. Any unrecognized property is saved as value or object tree represented as map-lists.
