### ISSUE TITLE
Create our own metrics publisher for Graphite

### ISSUE THREAD

**Issue by derek63** [lightblue-platform/lightblue-core#293]
Since we are having trouble with using Servo to publish Hystrix metrics to Graphite.  Essentially this just needs to push text to a socket in the following format

prefix.metricName value timestamp\n

**Comment by jewzaam** [comment]
Clarification, we need to publish to collectd.  Are you sure on the format?  That's the same as what is done straight to graphite today.

----- Original Message -----

**Comment by dcrissman** [comment]
Found this existing plugin, however it does not appear to be maintained any more. Also, does not support maven and is not in central repo.
* collectd plugin to expose an api to java applications: https://collectd.org/wiki/index.php/Plugin:Java
* java api for above plugin: https://github.com/hyperic/jcollectd

netty-collectd appears to be able to decode and view only
* https://github.com/rhq-project/netty-collectd

**Comment by dcrissman** [comment]
Also exploring the possibility of writing to statsd over their java client: https://github.com/etsy/statsd/wiki
