### ISSUE TITLE
Simplify fetch all query

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#300]
Fetch all is a very common use case. Following syntax:
    
    ...entityName/1.0.0?Q=objectType:entityName

is redundant and makes modifying those queries a little more effort than it has to be.

**Comment by jewzaam** [comment]
How about if a query is not specified it is treated as a fetch all?  Projections could still be applied if specified.  This means changes to the core query language logic I think.  Maybe it would simply translate an empty query to the query given above, objectType eqauls the given entityName.

**Comment by bserdar** [comment]
How about $all? We have this keyword as part of the update expression, we
can move it to query expressions. A query of the form

query: $all

would return everything.

**Comment by jewzaam** [comment]
Is that referred over making query optional?  It's more explicit, yes.  I guess thinking of what other languages do, if there are no conditions supplied it's implied to fetch all, example being SQL select without a where clause.

**Comment by bserdar** [comment]
It makes it more explicit, and prevents deleting everything by mistake in
case you send a DELETE request without a query.

**Comment by jewzaam** [comment]
We could make this change only for find, make query required for delete.

----- Original Message -----

**Comment by bserdar** [comment]
I think it is reasonable to make query optional for find.

**Comment by alechenninger** [comment]
+1 to optional find query

**Comment by bserdar** [comment]
Query is now optional.
