### ISSUE TITLE
Should hystrix/graphite stuff be in core?

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#312]
There's nothing in core that depends on these. They are here because they are used by implementations, and rest. Should these be moved to those individual projects instead?

**Comment by luan-cestari** [comment]
I agree. I think we used to have a shared class that used that dependency on core and after the problem with servo we moved it

**Comment by jewzaam** [comment]
The only place using it is rest.  I don't think applications will use it ever.  It makes sense to move it.

**Comment by jewzaam** [comment]
This has been broken into new module `hystrix` in core. Could easily be broken out to new repo if we wanted.

**Comment by luan-cestari** [comment]
I think it sound good as we don't use it on the core and  we don't want to messh any issue from core to the hystrix/servo/graphite or even if we want to have different versions from theses different things (core and hystrix). Would it be a project with a single module or it would be just a single simple project?:

**Comment by jewzaam** [comment]
I think a simple project would do nicely.  I think there are some other projects we have outside of lightblue that could benefit from having metrics pushed to graphite via statsd, though they don't use hystrix today.  Maybe some other utilities would be developed in the new repo long term.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/issues/637
