### ISSUE TITLE
Sonar - Review the inactive rules  in the sonar and complementary rules in other sonar instances

### ISSUE THREAD

**Issue by luan-cestari** [lightblue-platform/lightblue-core#320]
We could review if some inactive rules should be active again or the other way around. I also made this sheet https://docs.google.com/a/redhat.com/spreadsheets/d/1gnVUe2DLWbPXl5AgNk4g_pEzw8TsqCt3DqSP6oOjP9Q/edit?usp=sharing where we can see other two public sonar instances which FindBugs have 607 rules (against the 419 in our case), for example, and maybe this should be investigated as well (due the additional rules but it can also help to review the active rules). Others sonar instances can be investigated as well.

**Comment by luan-cestari** [comment]
This issue is part of https://github.com/lightblue-platform/lightblue-core/issues/169

**Comment by jewzaam** [comment]
That google sheet isn't visible outside of our org.  If it's part of this github issue it should be made visible/public, yes?

**Comment by luan-cestari** [comment]
I noticed, but for this specific case I think it make sense, as I can't
attach the sheet here and the sonar instance is managed by us, so only us
can make the change. Also, I just made a summary to help, not really
necessary for this issue.
