### ISSUE TITLE
Querying association fields does strange things

### ISSUE THREAD

**Issue by jblashka** [lightblue-platform/lightblue-core#365]
Setup:
[jA Metadata](https://gist.github.com/jblashka/7752ceeaa265b0198ef8#file-ja-metadata)
[jB Metadata](https://gist.github.com/jblashka/7752ceeaa265b0198ef8#file-jb-metadata)
[jA Sample Data](https://gist.github.com/jblashka/7752ceeaa265b0198ef8#file-ja-data)
[jB Sample Data](https://gist.github.com/jblashka/7752ceeaa265b0198ef8#file-jb-data)

4 jA documents & 2 jB documents. Each jB document is associated with a different pair of jA documents.

[Find Request 1](https://gist.github.com/jblashka/aa6cfb141599943108d4#file-1-find-request) - Pull in all jB documents and only the associated jA documents with a matching _id.
[Expected Results](https://gist.github.com/jblashka/aa6cfb141599943108d4#file-3-expected-results) - Both jB documents and only one jA document each
[Actual Results](https://gist.github.com/jblashka/aa6cfb141599943108d4#file-2-actual-results) - Both jB documents and no associated jA documents

[Find Request 2](https://gist.github.com/jblashka/47b5c4f321df978a61b2#file-1-request-2) - Pull in all jB documents and all jA documents with an objectType of jA (i.e. all of them)
[Expected Results](https://gist.github.com/jblashka/47b5c4f321df978a61b2#file-3-expected-results) - Both jB documents and the two associated jA documents
[Actual Results](https://gist.github.com/jblashka/47b5c4f321df978a61b2#file-2-actual-results) - Four jB documents (each one has been duplicated) and no associated jA documents

**Comment by bserdar** [comment]
What is the projection?

The query determines what documents will be retrieved. Once a document is
retrieved, if the projection does not include the associations, the
associations won't be retrieved. So, Q1 response looks correct if the
projection did not explicitly requested jA. An include * recursively won't
do, you have to explicitly project jA, or something under it.

Q2 resuls look wrong, though if the projection did not include jA, you
won't get jA.

**Comment by jblashka** [comment]
The projection for both queries is
`"projection": [{"field":"*", "recursive": true},{"field":"A"}]`
