### ISSUE TITLE
Is the call to getMetadata required here?

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#378]
It makes  a sort of circular call between the two methods and I don't see the value.

https://github.com/lightblue-platform/lightblue-core/blob/master/config/src/main/java/com/redhat/lightblue/config/LightblueFactory.java#L261

**Comment by bserdar** [comment]
It doesn't look like it is necessary. Remove and see if it breaks anything.
If it does, we can maybe find a better solution.

**Comment by luan-cestari** [comment]
IIRC it is. Se notice that during the integration tests, so if you remove,
better build all the projects to seek any impact

Em sáb, 18 de abr de 2015 00:44, Burak Serdar <notifications@github.com>
escreveu:

**Comment by dcrissman** [comment]
I built locally and couldn't find a project that had issues. Submitting PR.

**Comment by dcrissman** [comment]
Sure enough, when this change went in it broke com.redhat.lightblue.rest.crud.ITCaseCrudResourceTest.testFirstIntegrationTest.

Not sure why local tests didn't find that. I issued a revert PR for now. 

I guess the question now is, if you call getJSONParser, should you assume the metadata is loaded? or vice-versa?

**Comment by dcrissman** [comment]
Spoke with @bserdar and that is not an assumption that should be made. You should be able to use the parser without metadata loaded.

The reason metadata was being loaded there is because hooks need to be registered on the Factory. This seems that it will be a complicated fix to untangle. For now I will spin off a new issue to discuss.

**Comment by dcrissman** [comment]
#382 created to continue the discussion.
