### ISSUE TITLE
Required constraint works inconsistently for insert and update

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#383]
It appears that required fields can be null when inserting, but this is not allowed when updating. Strangely enough, updates are failing for fields which are not being updated.

Steps to reproduce can be found on https://mojo.redhat.com/docs/DOC-1025645.

**Comment by jewzaam** [comment]
@paterczm please post the steps publically (gist or in-line in issue).

**Comment by paterczm** [comment]
@jewzaam I'm using real data in steps to reproduce. I don't feel comfortable posting it here.

**Comment by jewzaam** [comment]
To verify this issue is fixed we'll need a test, yes?  Can you obfuscate and create an example that is suitable for a unit test?

**Comment by bserdar** [comment]
There is a unit test for it: MongoCRUDControllerTest.insertTest_nullReqField

**Comment by paterczm** [comment]
Verified.
