### ISSUE TITLE
Errors from parsing extensions should not kill lightblue

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#384]
We should still get an exception logged, but lightblue the application should load without the extension.

**Comment by bserdar** [comment]
I think all initialization errors are fatal errors.

**Comment by dcrissman** [comment]
@derek63 This came out of our discussion yesterday. Is there any more detail that you could add?

**Comment by bserdar** [comment]
If there are no objections, i'll close this issue. I still think initialization errors should be fatal.
