### ISSUE TITLE
Need metadata caching

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#387]
Define a caching interface, and use it for metadata in core. Can use infinispan cache, a simple hashtable, etc. There should be a reasonable ttl for entities, and metadata updates should either invalidate or update the cache as well. Needs to be done such that no unnecessary dependency is introduced at the core level. Metadata configuration should initialize the cache.

We're spending about 90msecs for a find call, 60 of which is used to lookup metadata.

**Comment by jewzaam** [comment]
Invalidation of the cache could be a problem.  Metadata updates happen in the metadata svc, which is not necessarily co-located with data (crud) svc.  An API could be created to support this on crud but that means a distributed cache, not simple hash-table.  Svc access is via load balancer, direct access is not allowed in our architecture.

**Comment by bserdar** [comment]
Do you see a problem with using infinispan?

**Comment by jewzaam** [comment]
Not a fan of distributed cache.  Additionally, our nodes are not clustered.

**Comment by bserdar** [comment]
This is implemented.
