### ISSUE TITLE
Shorten metric names published to statsd

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#390]
All hystrix command metrics include the string "HystrixCommand" in it.  With that and the prefix we have configured right now ("lightblue") we end up metric names that are too long (see bug https://github.com/collectd/collectd/issues/970).  

I propose we shorten metric names by removing the string "HystrixCommand_" from what is published to statsd.  Additionally, we could remove the prefix we have configured, but that's a hieradata change and not a code change (just noting here).

**Comment by bserdar** [comment]
No longer relevant.
