### ISSUE TITLE
This conditional duplicates itself

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#392]
Should the condition only be listed once, or was something else suppose to be checked?

https://github.com/lightblue-platform/lightblue-core/blob/master/crud/src/main/java/com/redhat/lightblue/crud/DocCtx.java#L122

**Comment by luan-cestari** [comment]
@dcrissman Not sure the exactly problem of this issue. It creates a copy so the document can be changed without affecting the original document. What is the issue of that line? What it also needs to check there?

**Comment by bserdar** [comment]
It doesn't repeat itself. Compares to null, and this.
