### ISSUE TITLE
Maven dependency changes prevent wars from deploying

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#403]
https://github.com/lightblue-platform/lightblue-core/commit/b54d138a1173885e27ca482059912c0d6ed08599 removed hystrix-metrics-event-stream.jar. After that change, I'm seeing ```java.lang.ClassNotFoundException: com.netflix.hystrix.contrib.metrics.eventstream.HystrixMetricsStreamServlet``` during crud or metadata war deployment (deployment is unsuccessful).

I would restore hystrix-metrics-event-stream.jar myself, but I don't know what was the purpose of those changes and where this dependency should belong now.

**Comment by dcrissman** [comment]
@luan-cestari I believe ran a maven cleanup script to remove unnecessary dependencies. Dependencies that were not explicitly required would have been removed, likely taking implicit run time dependencies with it.

**Comment by luan-cestari** [comment]
It is exactly what @dcrissman said. I just merged the @paterczm 's PR.
