### ISSUE TITLE
Projection match does not work for null values

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#406]
If you filter array elements by X field with null value, no array elements are included in the response, even though array elements with X=null exist for documents returned by the query.

**Comment by bserdar** [comment]
FieldComparisonEvaluator.evaluate() needs to be fixed. It has to check if
the value in the query is a NullNode before evaluating it using Type, and
getting null.

**Comment by bserdar** [comment]
This turned out to be much more fundamental than I initially though. Type
comparisons did not handle NullNodes.
