### ISSUE TITLE
Create hook that will automatically update lastUpdatedBy and lastUpdatedDate fields if they exist

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#410]

**Comment by bserdar** [comment]
Instead, make it a constraint.

**Comment by jewzaam** [comment]
What would this constraint be called?  This seems pretty simple to knock out and would be useful.  Would it be two constraints or just one?  It could inspect the data type to determine what to populate.

**Comment by jewzaam** [comment]
And what about on insert for fields like creationDate and createdBy?

**Comment by bserdar** [comment]
There is now a CurrentTime generator to do this.
