### ISSUE TITLE
required constraint validation behaves wrong on save

### ISSUE THREAD

**Issue by ykoer** [lightblue-platform/lightblue-core#423]
currently child fields with required constraints are not ignored when the parent is null.
Example:

    "fields" : {
      "parent1" : {
        "type" : "object",
        "fields" : {
          "child1" : {
            "constraints" : {
              "required" : true
            },
            "type" : "string"
          },
          "child2" : {
            "constraints" : {
              "required" : true
            },
            "type" : "string"
          }
        }
    }

"parent1": null is causing
    
    "rest/SaveCommand/operationalProduct/save(operationalProduct:1.0.4-SNAPSHOT)/validateDocs/validateDoc/parent1.child1/required"
    "rest/SaveCommand/operationalProduct/save(operationalProduct:1.0.4-SNAPSHOT)/validateDocs/validateDoc/parent1.child2/required"

**Comment by bserdar** [comment]
No longer an issue.
