### ISSUE TITLE
Support querying multiple entities at one time.

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#424]
We've been finding that very chatty service requests mean a slow response because of the time on the wire.  The more requests that can be made at one time is better, or just getting all the data required at one time.  Going even further would be getting data for multiple entities at one time.  Today the query language supports only one since entity and version are at the top level of the lightblue request.  A requirement with this is keeping it as a backwards compatible change.

Probably would mean moving the entity + version into the query section of the request.  Make the query include an array of queries?  And if a single query object is submitted it's the current query spec?

**Comment by bserdar** [comment]
A way to implement this is to come up with a "batch request":

   BatchResponse[] batchRequest(BatchRequest[] requests)

where:

BatchRequest:
      - requestId
      - operation
      - the request

BatchResponse:
      - requestId
      - response

This can be done without touching lightblue core, at the rest level. Define
a new REST api for this, and call the back-end in a loop.

**Comment by alechenninger** [comment]
What about being able choose between an ordered and parallel batch? If the batch was all long(ish) running queries, running them in parallel would be a potentially significant performance boost. A client can do this without a batch of course, but then they incur the network traffic cost of multiple requests.

Something like...
BatchRequest:
      - requestId
      - operation
      - the request
      - mode: ordered or parallel (ordered by default)

Of course, running them in parallel wouldn't be as simple to implement.

**Comment by jewzaam** [comment]
Parallel operations could be handled automatically.  It gets tricky if
there's a mix of operations and when entities have associations though.  We
could do some very simple optimizations to start with such as make all
queries in a batch run in parallel if all the operations are "find".  And
work out the rest of it later.  I suspect allowing the client to override
this could have unintended side effects as the order of execution would be
very important for those mixed batch scenarios.

**Comment by bserdar** [comment]
Lets implement this in core, not in rest, because associations can use
something like this as well.

As for concurrency: initially we can simply run things in a single thread,
but for multi-threading, the simplest approach is to run all series of
finds in separate threads, and wait for those to be completed for updates.
Updates would be done one at a time. Parallelizing updates might be
problematic if an update to an entity triggers updates to other seemingly
unrelated entities (i.e. esb)
