### ISSUE TITLE
Allow missing projection?

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#470]
Not sure if I even like this idea, but the idea is that passing no projection at all would be equivalent to:

```json
"projection": {
    "field": "*",
    "include": false
  }
```

... But honestly I'd probably rather be explicit and say "give me nothing." Perhaps others feel differently.

**Comment by bserdar** [comment]
Empty projection already means "give me nothing". We just have to not complain about it.

**Comment by jewzaam** [comment]
@bserdar if you do not include "projection" you get an error:  "errorCode":"mongo-crud:NullProjection","msg":""

If by "empty" projection you mean "projection" field with an empty body you get an error:  "errorCode":"rest-crud:RestFindError","msg":"Error during the parse of the request"

If by "empty" projection you mean "projection" field with an empty array you are correct, there is nothing projected.

**Comment by bserdar** [comment]
projection: {} is invalid. The error is correct.

projection: [] is valid, it is empty projection

projection:null should work, i'll fix that. It should not return anything.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-mongo/pull/210
https://github.com/lightblue-platform/lightblue-core/pull/581
