### ISSUE TITLE
Hook framework should catch unchecked exceptions and log them

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#486]
Hook failures should not impact response to client.  Catch any exceptions and log them.

**Comment by BVulaj** [comment]
Are we saying catch as in squash them?  The best I think we can hope for is to catch-all RTE and log to ERROR.  Is that what was on your mind?

**Comment by jewzaam** [comment]
Yes.  All hooks are post lightblue CRUD operations.  Therefore we shouldn't have the request fail from a client point of view for the hooks.  But, log them so we don't loose it.

**Comment by BVulaj** [comment]
See PR #504. I believe that test shows this already working as expected.

**Comment by jewzaam** [comment]
I think you mean https://github.com/lightblue-platform/lightblue-core/pull/507
ack! closing
