### ISSUE TITLE
Hook failure shouldn't prevent other hooks from being processed

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#487]
If two hooks are configured, A and B, failure in one of those hooks should not cause the other hook to not process.  Meaning, if hook A is processed first and fails, hook B must still be processed.

Hooks are not chained together and have not inter-dependencies!

**Comment by BVulaj** [comment]
Re: PR #507 again - closeable?

**Comment by jewzaam** [comment]
yup
