### ISSUE TITLE
Mediator doesn't know backend will generate _id field.

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#489]
Replaces https://github.com/lightblue-platform/lightblue-audit-hook/pull/55

"If _id is required for an identity, the mediator doesn't know _id will be generated by the backend, and fails in constraint validation."

**Comment by jewzaam** [comment]
While this is a bug, could our immediate issue be fixed by removing the identity constraint from _id in the audit entity?  Audit doesn't care, backend will take care of it.

**Comment by bserdar** [comment]
It should be fixed already.

**Comment by dcrissman** [comment]
Fix was in https://github.com/lightblue-platform/lightblue-mongo/pull/166
