### ISSUE TITLE
Update array projection's "project" field to be consistent

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#493]
I think in all places other than array projection we use the name "projection" instead of "project".  This caused confusion in the client which assumed consistent use of "projection" (see https://github.com/lightblue-platform/lightblue-client/pull/173).  We could update to support either "project" or "projection", deprecate "project" and eventually get rid of it.  What do you think?

**Comment by bserdar** [comment]
+1

**Comment by bserdar** [comment]
Fixed https://github.com/lightblue-platform/lightblue-core/pull/503
