### ISSUE TITLE
Support Range with no upper bounds

### ISSUE THREAD

**Issue by BVulaj** [lightblue-platform/lightblue-core#497]
Support the ability to define a starting index with no upper bounds.  Allow use of 0, -1 or null to signify this.

```javascript
{
  "query": {
  	...
  },
  "projection": {
    ...
  },
  "range": [5, -1]
}
```

**Comment by bserdar** [comment]
lets assume if second element of the range is null or <0, is means unbounded.

**Comment by jewzaam** [comment]
What about updating the spec? Right now it's minItems: 2 but it could be changed to minItems: 1

https://github.com/lightblue-platform/lightblue-core/blob/d165e58f510a3f5c2ace7a31713158350e5c0fa4/query-api/src/main/resources/json-schema/projection/range.json#L27

**Comment by bserdar** [comment]
When there is only one item, is it from, or to?

**Comment by BVulaj** [comment]
My intention with the issue was for it to be the lower bound, or start
index.

But, without proper doc, or some clever wording, I could see it being
confusing and it maybe looking like an upper bound, or max items.

-Brandon

**Comment by jewzaam** [comment]
Then let's be specific.  How about deprecate the array and do an object
with fields "from" and "to".

**Comment by bserdar** [comment]
Why deprecate? This is just the input language, nothing changes at the back
end. We can support all of:

range: [from,to]
from: number
to:number
maxItems: number

So it could be a range, from-to, from-maxItems

**Comment by jewzaam** [comment]
Ok.

**Comment by bserdar** [comment]
This has been implemented.
