### ISSUE TITLE
Update delete queries don't support references

### ISSUE THREAD

**Issue by ykoer** [lightblue-platform/lightblue-core#501]
I have a reference query problem again. I would like to disable all users using a field from of a referenced document (its cdh party number in the example below)
But I am always getting:

    metadata:InvalidFieldReference","msg":"legalEntity in legalEntities.*.legalEntity.cdhPartyNumber"}]}

    DataUpdateRequest dur = new DataUpdateRequest(LBUser.ENTITY_NAME, LBUser.ENTITY_VERSION);
    dur.where(Query.arrayMatch("legalEntities", Query.withValue("legalEntity.cdhPartyNumber", Query.eq, "12345")));
    dur.updates(Update.set("status", LBUser.Status.disable));
    dur.returns(Projection.excludeField("*"));

I tried also

    dur.where(Query.withValue("legalEntities.*.legalEntity.cdhPartyNumber = " + cdhPartyNumber));

but same

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/pull/502
