### ISSUE TITLE
Unable to deploy rest apps on wildfly

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#51]
Was writing up docs on how to deploy to wildfly and hit a few issues that I was able to solve easily.  But now I'm getting this error:

Caused by: java.lang.ClassNotFoundException: javax.json.JsonArray from [Module "org.jboss.resteasy.resteasy-json-p-provider:main" from local module loader @38beb946 (finder: local module finder @7175bfc4 (roots: /usr/share/wildfly/modules,/usr/share/wildfly/modules/system/layers/base))]

Kinda giving up for now.  If anybody has any ideas please let me know what I can try.  Didn't want to spend much time on it right now.  Suspect something isn't setup in the modules, EAP6 provides this in a different way I guess.

**Comment by maslovalex** [comment]
just came across the same problem with our application (fc21 wildfly-8.1.0-3).

Beside those missing symlinks problems, there is at least one more issue in module `/usr/share/wildfly/modules/system/layers/base/org/glassfish/javax/json/main` which is an alias for `javax.json.api`.

I had to create 2 more symlink and add 2 lines to module.xml to be able to deploy my war.
Hope it solves your deployment also.

```
# ln -s /usr/share/java/jsonp/jsonp-api.jar jsonp-api.jar /usr/share/wildfly/modules/system/layers/base/org/glassfish/javax/json/main/jsonp-api.jar`
# ln -s /usr/share/java/jsonp/jsonp-jaxrs.jar jsonp-api.jar /usr/share/wildfly/modules/system/layers/base/org/glassfish/javax/json/main/jsonp-jaxrs.jar`
$ cat /usr/share/wildfly/modules/system/layers/base/org/glassfish/javax/json/main/module.xml
```
```
<module xmlns="urn:jboss:module:1.3" name="org.glassfish.javax.json">

    <properties>
        <property name="jboss.api" value="private"/>
    </properties>

    <dependencies>
    </dependencies>
    <resources>
        <resource-root path="jsonp.jar"/>
<!-- ADDED >>>> -->
<resource-root path="jsonp-api.jar"/>
<resource-root path="jsonp-jaxrs.jar"/>
<!-- <<<<< -->
    </resources>
</module>
```

**Comment by jewzaam** [comment]
Thanks for the note @maslovalex.

@alechenninger you solved deployment to wildfly specifically in arquillian or standalone as well?

**Comment by jewzaam** [comment]
Added an issue to verify our documentation and update if these changes are needed.

https://github.com/lightblue-platform/lightblue-docs-developer/issues/24

**Comment by alechenninger** [comment]
@jewzaam Just with arquillian, I didn't try standalone. And honestly when I did it with Arquillian it "just worked" using the embedded container. Now, there were some problems with the existing tests, but I think that was more of classpath differences when reading resource files between the Weld container and Wildfly embedded than a problem with the deployment.
