### ISSUE TITLE
Upgrade to Java 8

### ISSUE THREAD

**Issue by BVulaj** [lightblue-platform/lightblue-core#515]
Java 8 lambdas and streams would provide some nice ease-of-development features.

**Comment by jewzaam** [comment]
For a proper supported deployment of openjdk 1.8 we need to upgrade to JBoss EAP 6.4.1+.  We've been building on travis with 1.8 for a long time, so this is really the only thing holding it up.

See https://access.redhat.com/articles/111663

**Comment by jewzaam** [comment]
Looks like the latest version is EAP 6.4.4 which translates to jbossas-standalone RPM version 7.5.4 per https://rhn.redhat.com/errata/RHSA-2015-1905.html

I put in a ticket internally requesting this release be made available to us for use.

**Comment by jewzaam** [comment]
EAP 6.4.4 repo is ready internally.  Added a card to trello to track upgrade and testing.  Once confirmed we can switch out source to build with 1.8.  We will have to drop the travis 1.7 build as well since 1.8 features will break those builds.

**Comment by alechenninger** [comment]
Playing devil's advocate here, is it worth dropping ability for folks to run Lightblue on Java 1.7? I know internally that will be fine, but perhaps it'd be a good idea to keep accessibility as easy as possible for future external consumers (that is, supporting Lightblue on 1.7 and 1.8).

**Comment by jewzaam** [comment]
There's no point in upgrading, really, if we don't use the features of java
1.8.  And if we use 1.8 specific features it won't be backwards compatible
so... I don't see a problem moving forward with 1.8 honestly.  It's been
out for over 1.5 years now.  Probably makes sense to consider keeping 1.7
support in the client at least, but for the server side components I'd
rather update.

**Comment by alechenninger** [comment]
How soon do you expect to upgrade? I'm currently using 8 features in https://github.com/esbtools/lightblue-notification-hook but I don't have to if the upgrade won't happen for a while.

**Comment by jewzaam** [comment]
It's a matter of having time to upgrade our dev env and test.  Right now we just don't have time.

@paterczm having said this would it be an option to try this upgrade and see what happens with some of the stability issues seen lately?  or is that just another variable to make it that much more exciting (read: painful).

**Comment by jewzaam** [comment]
We've upgraded 1/2 of dev nodes to EAP 6.4.5 with openjdk 1.8.0.  Will see how it goes and eventually update all nodes in all envs.  Then we'll be able to swap over to builds with 1.8.

**Comment by alechenninger** [comment]
Awesome, thanks! I'll keep moving along with 1.8 then.

**Comment by alechenninger** [comment]
Did you upgrade the other half of nodes yet? Just curious on this progress / should we keep developing the hook with JDK8.

**Comment by jewzaam** [comment]
The jdk8 nodes are out of rotation at this time.  I don't know why.  But it
means we haven't confirmed things are good with them.  No we have not
updated the remainder of the nodes.
