### ISSUE TITLE
RFE: Embedded "lightblue container" for unit testing

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#52]
I can unit test EJB/Hibernate applications by using embedded EJB container and an in-memory sql database. I would like to have similar ability for applications using lightblue (in memory mongodb and embedded "lightblue container"). I understood you have something like that working already for lightblue unit tests, it just needs to be documented.

**Comment by dcrissman** [comment]
We could create a junit external resource for an in-memory sql database.
Example: https://github.com/lightblue-platform/lightblue-mongo/blob/master/test/src/main/java/com/redhat/lightblue/mongo/test/MongoServerExternalResource.java

Then we could do something like this for your test cases. It doesn't use arquillian, but it does stand an in-memory version of lightblue that will respond to calls via the rest layer.
https://github.com/lightblue-platform/lightblue-ldap/tree/master/lightblue-ldap-integration-test

**Comment by dcrissman** [comment]
With the advent of https://github.com/lightblue-platform/lightblue-test-utils, does that essentially cover the intent of this issue?

**Comment by paterczm** [comment]
Yes.
