### ISSUE TITLE
Generator on optional object results in util:IsNotAContainer

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#541]
We have an entity `bob` with an optional object `foo`.  On that object is a creationDate with a genrator.  If the optional object is null or not set the following is thrown:

```
java.lang.RuntimeException: com.redhat.lightblue.client.response.LightblueResponseException: Lightblue exception occurred: {"status":"ERROR","modifiedCount":0,"matchCount":0,"errors":[{"objectType":"error","context":"rest/InsertCommand/bob/insert(user:0.0.1)","errorCode":"crud","msg":"fooutil:IsNotAContainerfoo.creationDate"}]}
	at com.redhat.lightblue.client.response.DefaultLightblueDataResponse.<init>(DefaultLightblueDataResponse.java:28)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:226)
	at com.redhat.lightblue.client.http.LightblueHttpClient.data(LightblueHttpClient.java:232)
...
```

This is a mocked up msg value based on real exception.  Note the text runs together because of 
https://github.com/lightblue-platform/lightblue-core/blob/master/util/src/main/java/com/redhat/lightblue/util/JsonDoc.java#L559

It is read as parent "foo" is not a container for field "foo.creationDate".

**Comment by bserdar** [comment]
This should have been fixed couple of days ago do you have that fix
deployed?

**Comment by jewzaam** [comment]
I did pull the latest.  I have reproduced by taking the emails array in user-complex.json and swapping the elements so the one with empty validation field is first.

**Comment by jewzaam** [comment]
See https://github.com/jewzaam/lightblue-core/tree/fix-541-generator-on-optional-object

**Comment by jewzaam** [comment]
In my branch I missed updating one of the indexes.  It looks like it's higher up the stack then.  Maybe in the generator logic.  So my branch is useless, it's something using that API.

**Comment by jewzaam** [comment]
I assumed in this particular code base we'd be using latest core snapshot.  It wasn't because it was a transient dependency.  After explicitly adding the dependency this works.
