### ISSUE TITLE
null array elements are treated inconsistently

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#548]
PUT /insert/foobar
```json
{
 	"projection": {
 		"field": "*",
 		"include": true,
 		"recursive": true
 	},
 	"data": {
              "arrayfield": [null]
        }
}
```
returns

```json
{
"processed": [
  {
    "arayfield": [],
    "arrayfield#": 1
  }
]
}
```

The null array element is not visible in query results. The only indication that it's there (it is created in mongo) is the array length field.

Since lightblue treats null as non existing, I think it should not be possible to add null elements to arrays.

**Comment by bserdar** [comment]
This should be fixed after 2c606fc3
