### ISSUE TITLE
Possible to upgrade jackson version?

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#557]
As far as 2.x versions go, 2.6.4 is most stable with new JDK8 date/time types. It's nice to use these in model objects instead of deprecated `Date` type (which is much less nice to use).

This affects the notification hook where I would like to use JDK8 date/time types in the model: https://github.com/esbtools/lightblue-notification-hook

Not huge deal, but would help.

**Comment by alechenninger** [comment]
I should have said that the current version being used is broken with JDK8 date/time types. Admittedly I forget exactly in what way but I do know that I had to upgrade.

**Comment by alechenninger** [comment]
The bug I'm running into in the older version is this: https://github.com/FasterXML/jackson-datatype-jsr310/issues/29

**Comment by alechenninger** [comment]
Actually, let me see if that version of jackson-datatype-jsr310 can be used with jackson 2.5.3...

**Comment by alechenninger** [comment]
...nope, versions must match.

**Comment by dcrissman** [comment]
@alechenninger This change was merged today

**Comment by bserdar** [comment]
Core still doesn't recognize jdk8 datetypes though.

**Comment by alechenninger** [comment]
Thanks!

I guess hooks can just include the jdk8 module in their jar if they need it.
