### ISSUE TITLE
Support hierarchy of objects of arbitrary depth

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#559]
In defining some metadata in September we talked about having references to a pre-defined object structure that could be reused.  This would mean two instances of this object in different places in one metadata wouldn't have to maintain separate structures and try to keep them identical.

If this pre-defined object could reference itself we could setup a hierarchy by defining a child array with a type for that same object.

Maybe something like this, though we need to discuss if the definition would go in entityInfo or schema.  If it in schema it's versioned.  Given it has field structure in it, it should be versioned.
```javascript
{
    "entityInfo": {
        "definitions": [
            {
                "name": "reusableObject",
                "fields": {
                    ...,
                    "children": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "constraint": {
                                "definition": "reusableObject"
                            }
                        }
                    }
                }
            }
        ],
        ...
    },
    "schema": {
        "fields": {
            "myObject": {
                "type": "object",
                "constraint": {
                    "definition": "reusableObject"
                }
            }
        },
        ...
    }
}
```

**Comment by alechenninger** [comment]
One of things I have found with using the lightblue-java-generator and starting from Java to metadata, is problems like this go away. You can organize your Java classes however you want, reuse them wherever, and the metadata is generated with the embedded objects unaware of their reuse.

**Comment by bserdar** [comment]
Arbitrary depth metadata is problematic. There is a lot of code that depends on depth-first traversal of metadata tree, and self-referencing structures will break them. If self-referencing structures are to be supported, we have to change how metadata is used, namely, we should never iterate metadata, but iterate data and relate individual nodes back to its metadata. Not impossible.

**Comment by ykoer** [comment]
How about we provide a depth limit in the metadata. Lightblue would pre-process the user defined metadata and then create an internal version of it with the complete hierarchy. Not nice, but I think its easier to implement.

**Comment by jewzaam** [comment]
This would be the same as copying objects as children in metadata, I
probably wouldn't bother spending time to implement a limited depth
hierarchy.  My thinking is we'd still have a hard limit on the depth, which
is one of the problems.  The other being the redefinition of the objects,
which while a bit of a pain to deal with today isn't too bad with careful
copy and paste and peer review.
