### ISSUE TITLE
Fix persistence of not recognized fields in metadata entityInfo

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#585]
Got some metadata from another team today and they had a string field in their entityInfo called "maintainers", value was their team email list.  I like this idea but would make it an array of strings.  Right now this doesn't break the submission of metadata but it isn't saved.

**Comment by bserdar** [comment]
Anything that is not recognized should be saved as a "property". Probably
that is broken.

**Comment by jewzaam** [comment]
Guess it's broken.  Didn't get saved in dev for sure.  Will update the subject.

**Comment by bserdar** [comment]
Fixed now.
