### ISSUE TITLE
Slow running query

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#588]
users is a reference field.

"query": {
		"$and": [{
			"field": "userId",
			"op": "$in",
			"values": [3, -3]
		}, {
			"field": "users.*.personalInformation",
			"op": "=",
			"rvalue": null
		}]
	},

**Comment by paterczm** [comment]
We backed away from using associations because of this and other bugs. I would need to check to see if we're not using them somewhere, but I don't expect this to affect performance.
