### ISSUE TITLE
Add ability to project and/or query for only matching element in array

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#607]
I frequently want to query for something that is inside of an entity, and just get that thing back. Projections to my knowledge do not currently support this. That is, if I am querying for a specific object element in an array using an array match query, I can only project as limited as all of the elements of that array, but really I just want the element that matched. Because I get all of them back, this means I need to do an addition search through the returned array to get the one element I queried for.

Is this supported currently? If not, maybe it is a feature worth considering?

Thanks!

**Comment by bserdar** [comment]
This is supported by re-querying it in projection: If you have a query Q on
an array field, you can project with { array: a, elemMatch:Q}

**Comment by alechenninger** [comment]
Oh wow I completely forgot projections could do that. Thanks!
