### ISSUE TITLE
Add update expression to remove primitive element in array by query

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#631]
Unless this is already possible, I did not see a way in https://jewzaam.gitbooks.io/lightblue-specifications/content/language_specification/update.html

**Comment by alechenninger** [comment]
Nevermind I think I can with $remove

**Comment by alechenninger** [comment]
So this is not working with primitives specifically, here's what I tried:

```json
{
  "query": {
    "field": "domain",
    "op": "=",
    "rvalue": "esb"
  },
  "update": {
    "$foreach": {
      "canonicalTypesToProcess": {
        "field": "$this",
        "op": "=",
        "rvalue": "Customer"
      },
      "$update": "$remove"
    }
  }
}
```

**Comment by kahoali** [comment]
@bserdar any thoughts on how trivial ( or not ) this would be to implement?

**Comment by bserdar** [comment]
It is not hard, a matter of prioritization atm. Is it urgent?

**Comment by kahoali** [comment]
Absolutely not urgent.

I'm in the process of documenting queries for routine operational/support activities and this would greatly simplify writing one of the queries. I'm mostly asking from the perspective of access/ease of use around the support case in question.

**Comment by alechenninger** [comment]
@BVulaj I don't think this is fixed, I am still getting this with the original query:

```json
{
  "objectType": "error",
  "context": "rest/UpdateCommand/eventHandlerConfig/update(eventHandlerConfig:0.1.0)/update",
  "errorCode": "metadata:InvalidArrayReference"
}
```

**Comment by bserdar** [comment]
Are you sure you are using the latest core?

**Comment by alechenninger** [comment]
Is this deployed to dev? I assumed since this was fixed 12 days ago it would be deployed by now

**Comment by BVulaj** [comment]
@snehagunta this also may be helpful for what you were looking at.

@alechenninger It should be in dev.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/blob/master/crud/src/test/java/com/redhat/lightblue/eval/UpdaterTest.java#L196
