### ISSUE TITLE
Sometimes "$in" query returns no results but "=" query does

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#640]
When I query like this...

```json
  "query": {
    "field": "_id",
    "op": "$in",
    "values": [
      "5723a232a0cc9b060ce70535"
    ]
  },
```

I get no results. But when I query like this...

```json
  "query": {
    "field": "_id",
    "op": "=",
    "rvalue": "5723a232a0cc9b060ce70535"
  },
```

I get one result.

It seems some fields are not affected. I can do the same kind of queries with "status" "$in" or "=" and both return results as expected.

**Comment by bserdar** [comment]
This is probably for only _id queries, and it has to do with special handling of _id in the mongo backend.

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-mongo/issues/286
