### ISSUE TITLE
Need API to get the next value from a generator

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#641]

**Comment by bserdar** [comment]
Also need support for getting multiple ids at once

**Comment by jewzaam** [comment]
Any specific authorization expected for these API's?  Right now sequence generated is basically authorized via entity and field access.  Considering this is similar to sequence advancement in a relational database it's rare to provide such access directly in an API.  Could the sequence data be exposed as an entity instead?  Then we have authz for the entity itself, if not for specific sequences.

**Comment by bserdar** [comment]
There will be auth. We can only expose these generators via the field names
they're defined in. So the request will be something like:

 GET /rest/data/generate/user/0.0.1/field=legalEntity.*.uid


We can allow this if the caller has entity read or write access.

**Comment by bserdar** [comment]
Fixed with:
https://github.com/lightblue-platform/lightblue-client/pull/292
https://github.com/lightblue-platform/lightblue-rest/pull/229
https://github.com/lightblue-platform/lightblue-core/pull/644
https://github.com/lightblue-platform/lightblue-core/pull/642
