### ISSUE TITLE
Overwriting value generator should insert value on any document update

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#649]
Consider lastUpdateDate:

```json
           "lastUpdateDate": {
                "constraints": {
                    "required": true
                },
                "type": "date",
                "valueGenerator": {
                    "configuration": {
                        "overwrite": true
                    },
                    "type": "CurrentTime"
                }
            },
```

It should be populated by the generator when any field in the document is updated, even though a value for lastUpdateDate exists prior to update.

**Comment by bserdar** [comment]
Try:
"valueGenerator": {
                   "overwrite": true,
                    "type": "CurrentTime"
                }

**Comment by paterczm** [comment]
Ah. Overwrite is inside configuration in pretty much all of our metadata. Metadata passes validation, because configuration element does exist in the json schema... Will fix.
