### ISSUE TITLE
Improvements to bulk processing

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#655]
- Lets have two types of bulk requests: ordered and unordered.
  requests: [ ...requests ] : ordered request
  unorderedRequests: [ ... requests.. ]: unordered requests

unorderedRequests should be executed in parallel, based on a set parallelism count,
- For ordered requests: consecutive insert/update of the same entity should be done in a single request
- For unordered requests: all inserts/updates on the same entity should be done in a single request

**Comment by paterczm** [comment]
If there are many save/insert requests, merge them into a single mongo call.

**Comment by paterczm** [comment]
@bserdar, do you see a value in having both ordered and unordered arrays of requests in a bulk request? If not, maybe a simple flag - unordered: true - will suffice?

**Comment by bserdar** [comment]
flag would work, should default to ordered:true to preserve existing
semantics

**Comment by paterczm** [comment]
> consecutive insert/update of the same entity should be done in a single request

When you say single request, do you mean mongo bulk operation?

**Comment by bserdar** [comment]
I mean a single CRUD request, which will be a single mongo bulk operation.
For instance:

bulkRequest: {
  insert entityA: { a, b, c },
  insert: entityA  { d, e, f }
}

can be
insert entityA: {a,b,c,d,e,f}

If the bulk request is unordered, all insert/save requests of the same
entity can be grouped into one. If it is ordered, only consecutive requests
can be grouped.

**Comment by paterczm** [comment]
How much value is there in server side merging of insert and save crud requests? It's something the client side implementation should take care of.

**Comment by bserdar** [comment]
Client side processing will not always take care of grouping requests.
There can be functions that build lightblue requests that are sometimes
called in different contexts to build a bulk request, or the request can be
submitted individually. So this optimization is useful though not essential.
