### ISSUE TITLE
A field with generator with overwrite: true cannot be set explicitly

### ISSUE THREAD

**Issue by paterczm** [lightblue-platform/lightblue-core#669]
Example:

```
"lastUpdateDate": {

    "type": "date",
    "description": null,
    "valueGenerator": {
        "type": "CurrentTime",
        "overwrite": true
    },
    "constraints": {
        "required": true
    }
},
```

There is no way to set lastUpdateDate to explicit value, which may be required e.g. when migrating data.

Perhaps overwrite should apply only to existing document (overwrite existing value), but still prefer the value in the update request?

**Comment by bserdar** [comment]
That'll cause more problems than it'll solve I think. If you read
something, modify fields other than the lastUpdateDate, and save it back,
it'll contain a lastUpdateDate, and won't update the field in the db.

**Comment by paterczm** [comment]
Yes, for save operations on existing data you'd need to nullify it explicitly to get it generated. I guess the question is what behavior is more intuitive. I assumed overwrite: true overwrites existing value, not value coming in the request.

**Comment by bserdar** [comment]
If you want to set it to null to get it generated, then set field
required:true, and overwrite false, and it'll be generated if it is null,
won't be touched it not null.

**Comment by paterczm** [comment]
Well, the whole point is that it's generated without specifying it explicitly. I proposed nullifying generated field only for the read-modify-save example you gave, when overwrite: true does not affect the value coming in request.

Perhaps you right, this is just replacing one problem with another. I'll think about it a bit more, maybe all we need to do is update the doc to better explain current behavior: http://docs.lightblue.io/cookbook/value_generators.html

**Comment by paterczm** [comment]
Done thinking about it. Closing.
