### ISSUE TITLE
NULL_RETURNS in QueryPlanChooser

### ISSUE THREAD

**Issue by jewzaam** [lightblue-platform/lightblue-core#694]
** CID 144031:    (NULL_RETURNS)
/lightblue-core/crud/src/main/java/com/redhat/lightblue/assoc/QueryPlanChooser.java: 206 in com.redhat.lightblue.assoc.QueryPlanChooser.assignQueriesToPlanNodesAndEdges(java.util.List, java.util.List)()
/lightblue-core/crud/src/main/java/com/redhat/lightblue/assoc/QueryPlanChooser.java: 221 in com.redhat.lightblue.assoc.QueryPlanChooser.assignQueriesToPlanNodesAndEdges(java.util.List, java.util.List)()
/lightblue-core/crud/src/main/java/com/redhat/lightblue/assoc/QueryPlanChooser.java: 222 in com.redhat.lightblue.assoc.QueryPlanChooser.assignQueriesToPlanNodesAndEdges(java.util.List, java.util.List)()

________________________________________________________________________________________________________
*** CID 144031:    (NULL_RETURNS)
/lightblue-core/crud/src/main/java/com/redhat/lightblue/assoc/QueryPlanChooser.java: 206 in com.redhat.lightblue.assoc.QueryPlanChooser.assignQueriesToPlanNodesAndEdges(java.util.List, java.util.List)()
200                             // entity can be assigned to a query plan node. If clauses
201                             // depend on multiple entities, their assignments may change
202                             // based on the query plan.
203                             LOGGER.debug("Conjunct has one entity");
204                             // Rewrite the query for that node
205                             QueryPlanNode node = qplan.getNode(entities.iterator().next());
>>>     CID 144031:    (NULL_RETURNS)
>>>     Calling a method on null object "node".
206                             RewriteQuery rw = new RewriteQuery(compositeMetadata, node.getMetadata());
207                             QueryExpression q = rw.rewriteQuery(c.getClause(), c.getFieldInfo()).query;
208                             AnalyzeQuery analyzer = new AnalyzeQuery(node.getMetadata(), c.getReference());
209                             analyzer.iterate(q);
210                             node.getData().getConjuncts().add(new Conjunct(q,
211                                     analyzer.getFieldInfo(),
/lightblue-core/crud/src/main/java/com/redhat/lightblue/assoc/QueryPlanChooser.java: 221 in com.redhat.lightblue.assoc.QueryPlanChooser.assignQueriesToPlanNodesAndEdges(java.util.List, java.util.List)()
215                         case 2:
216                             // There are two entities referred to in the conjunct
217                             // This clause can be associated with the edge between those two entities.
218                             // If the two entities are not associated, then the conjunct goes into the
219                             // unassigned queries list.
220                             Iterator<CompositeMetadata> itr = entities.iterator();
>>>     CID 144031:    (NULL_RETURNS)
>>>     Assigning: "node1" = null return value from "getNode".
221                             QueryPlanNode node1 = qplan.getNode(itr.next());
222                             QueryPlanNode node2 = qplan.getNode(itr.next());
223                             if (qplan.isUndirectedConnected(node1, node2)) {
224                                 LOGGER.debug("Conjunct is assigned to an edge");
225                                 QueryPlanData qd = qplan.getEdgeData(node1, node2);
226                                 if (qd == null) {
/lightblue-core/crud/src/main/java/com/redhat/lightblue/assoc/QueryPlanChooser.java: 222 in com.redhat.lightblue.assoc.QueryPlanChooser.assignQueriesToPlanNodesAndEdges(java.util.List, java.util.List)()
216                             // There are two entities referred to in the conjunct
217                             // This clause can be associated with the edge between those two entities.
218                             // If the two entities are not associated, then the conjunct goes into the
219                             // unassigned queries list.
220                             Iterator<CompositeMetadata> itr = entities.iterator();
221                             QueryPlanNode node1 = qplan.getNode(itr.next());
>>>     CID 144031:    (NULL_RETURNS)
>>>     Assigning: "node2" = null return value from "getNode".
222                             QueryPlanNode node2 = qplan.getNode(itr.next());
223                             if (qplan.isUndirectedConnected(node1, node2)) {
224                                 LOGGER.debug("Conjunct is assigned to an edge");
225                                 QueryPlanData qd = qplan.getEdgeData(node1, node2);
226                                 if (qd == null) {
227                                     qplan.setEdgeData(node1, node2, qd = qplan.newData());

**Comment by bserdar** [comment]
This is not semantically possible
