### ISSUE TITLE
Include principal in MDC

### ISSUE THREAD

**Issue by dcrissman** [lightblue-platform/lightblue-core#697]
This would allow logging to expose the principal associated with each log.

**Comment by bserdar** [comment]
MDC?

**Comment by dcrissman** [comment]
Some examples:
* https://blog.oio.de/2010/11/09/logging-additional-information-like-sessionid-in-every-log4j-message/
* https://github.com/candlepin/candlepin/blob/master/common/src/main/java/org/candlepin/common/filter/LoggingFilter.java

My feeling is that principal should be set in core, but my initial testing has not successfully worked with the log4j pattern. MDC uses a ThreadLocal under the hood (I guess), so it could just be that my value is being set on another thread.

**Comment by bserdar** [comment]
Core is multithreaded, so it'll be difficult to pass that from one thread
to the other.

A better option would be to have it in operation context, and pass to
logging explicitly

**Comment by dcrissman** [comment]
Fixed in https://github.com/lightblue-platform/lightblue-rest/pull/251
