### ISSUE TITLE
Enums values should probably be in schema, not entityInfo

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#698]
This scenario is common:

1. Client model object exists which uses an enum, and knows about values at the time of creation
2. Client can even use specific version
3. If new enum value is added, and data inserted with this new version, this can break clients expecting stable enum values

Effectively, to clients, right now enum types must really be treated as arbitrary string values since the valid values can change at any time across all versions.

**Comment by alechenninger** [comment]
@bserdar @jewzaam thoughts?

**Comment by paterczm** [comment]
Run into this this morning. Right now it's expected that clients can deal with unknown enums, either by using a simple string or an enum with 'unknown' field. The latter solution still gives you type safety.

As to your suggestion - what should Lightblue do, when a client requests a document which has an enum field with a value not present in schema version requested? If it returns null, it can break the client as well.

**Comment by alechenninger** [comment]
If enums are to be true enums, then changing the set of values is a
breaking change.

I think Google's protobuf enums all have concept of unknown values, but
they have the luxury of controlling the unmarshalling so they can build
that in. Lightblue clients would have to know to enforce this themselves.

We should confirm what latest version of protobuf does as a guide. Assuming
it still does the unknown value thing, consider this option: all lightblue
enums have a value "$unknown" built in. Schema versions which do not
support values in later or earlier schemas read these as unknown.

**Comment by jewzaam** [comment]
Adding enum values does not break it from a lightblue point of view.
Removing enum values does break it from a lightblue point of view if the find request validates the data in a field and finds a value that is no longer in there.  I don't think we do validation like this in find.
So from a lightblue centric point of view, assuming clients use lightblue API's directly and don't do validation themselves, enum changes don't break things.

The problem is with clients.  Enums in something like java are a validation on the client side.  It's a problem when that validation conflicts with the data found in lightblue.  Using a java enum on the client causes issues.  We know this.  My recommendation is don't use java enum.  Instead use a set of known values and expect/handle the case when an unknown value is returned.  This does not cover the case of a value being removed.  But that's not what we usually are faced with when this issue surfaces.

**Comment by paterczm** [comment]
@alechenninger 
> If enums are to be true enums, then changing the set of values is a
> breaking change

If that's how we define enums, then it already works as designed when client serializes to/from java enums :) 

> Assuming
> it still does the unknown value thing, consider this option: all lightblue
> enums have a value "$unknown" built in. Schema versions which do not
> support values in later or earlier schemas read these as unknown.

We could implement this behavior in the enum types (i.e. in the model, on the client side) right now. Not sure what value does it bring if Lightblue converts unknown enums to $unknown.

Untested example:

```java
    public enum  LBEnumType {
        value1("value1"),
        value2("value2"),
        unknown(null);

        private final String value;

        LBEnumType(String value) {
            this.value = value;
        }

        @JsonCreator
        public static LBEnumType fromValue(String value) {
            if (value != null) {
                for (LBEnumType e : values()) {
                    if (e.value.equals(value)) {
                        return e;
                    }
                }
            }
            
            return unknown(value); // not sure if that will work
        }

        @JsonValue
        public String toValue() {
            return value;
        }
    }
.

**Comment by alechenninger** [comment]
If enum constraint is to be treated as a growable set of valid strings, then leaving the values in entityInfo is fine, though inconsistent with other constraints. While maybe this is known to a few people, we have no code generation, and every enum field I have seen has been codified as an enum in Java, which is of course unsafe in this model. It's a reasonable thing to intuit, and tragically ubiquitous, and this is mainly where my complaint is with the current design: it's a "gotchya" that so far has "gotten" most if not everyone, even folks who have worked on/with lightblue for a while.

**Comment by jewzaam** [comment]
Maybe then an issue for the lightblue documentation on enum to note the
possible pitfalls with enum?  I don't think this is a problem unique to
lightblue, but it is worth pointing it out.

**Comment by paterczm** [comment]
Documentation update: https://github.com/lightblue-platform/lightblue-docs-user/pull/94

**Comment by alechenninger** [comment]
Is there any compelling reason to put this in schema? All I can think of is that it is inconsistent with other constraints which are parameterized in schema not entityInfo. I guess the other behavior difference is whether or not we would want the same version to be able to use new enums.

If no one finds these reasons compelling I think we can close the issue.
