### ISSUE TITLE
Association cycles using default versions is broken if entity occurs in the cycle with a given version

### ISSUE THREAD

**Issue by bserdar** [lightblue-platform/lightblue-core#715]
A -> A, association uses default version, but A is requested using a given version. Response is crud:MetadataAppearsTwice.

There is a question here: If A->A association uses the default version, and if A is loaded using a given version that is not the same as the default version, does the relationship use the given version, or the default version?

If the answer is "default version", then A->A relationship is only valid when we load the default version of A.

If the answer is "given version", then A->A defines a separate relation for each version of A.

I think associations using default versions should be evaluated using the given version of an entity. That is, if A -> A is done using default version D, and if A is read using a version V!=D, then the association uses version V, not D.

**Comment by jewzaam** [comment]
I agree with the assessment that if A->A uses default version D and A is loaded with non-default version V that association should be evaluated with the version V.

**Comment by bserdar** [comment]
This needs a bit more clarification. 

If default version of A is requested, then we load the default version of A, say 'v', and descend the association tree. If there are any cycles back to A using the default version, then we use 'v'. If there are any cycles back to A using any version other than 'v', we fail.

If some version 'x' of A is requested, then we load version 'x' of A, and descend the association tree. If there are any cycles back to A using the default version, then we use 'x' (not the default version of A). If there are any cycles back to A using any version other than 'x' or default, we fail.

If we are loading the metadata for A, and if there is a relation B->C
   - If B->C is defined using a default version, then we traverse the tree for A, and find out if there are any definite versions of C requested. If so, the definite version of C will be used for defaults. Otherwise, use the default version. (Implementation note: simply deferring loading of default versions of entities should achieve this)

**Comment by jewzaam** [comment]
Thanks, this sounds reasonable to me.
