### ISSUE TITLE
Add query to save as extra condition on top of implicit identity match

### ISSUE THREAD

**Issue by alechenninger** [lightblue-platform/lightblue-core#745]
Use case: I want to use save, but I want to use update-if-current pattern to detect concurrent modification.

For example:
1. I do a find
2. I update some data, do some complicated validation based on this update
3. Validation passes, so I want to save the data back. But, I don't want to save if if it is now stale since my find in step 1. So I want to to use update-if-current pattern with save operation.

Alternative is to express the update in 3 as an update expression instead.

@bserdar what do you think?

**Comment by bserdar** [comment]
That requires passing back the document version, and the client also has to
pass version back, so we can test. It is doable with some changes to the
client, and the response types.

**Comment by alechenninger** [comment]
@bserdar Hrm... you mean the document version from lightblue's existing concurrent mod detection? Honestly, if I could add a query to the save, I would just use lastUpdateDate=${current_lastUpdateDate_I_have_from_find_in_step_1}. This is how I've been implementing update-if-current client side for these kinds of find-then-update algorithms.

**Comment by bserdar** [comment]
lastUpdateDate is not guaranteed to work if two update requests come within
a millisecond. The only guaranteed way to make this work is to use the
version.

Maybe we can do something like this:
 - Add a flag to findRequest to retrieve document versions, so we can
return them, embedded in the document
 - For saveRequest, add an onlyIf option
    - If you have the version, you can use onlyIfVersion:<docVersion>
    - Or, you can use a predicate onlyIf:{field:lastUpdateDate, op:=,
rvalue:<date>}

**Comment by alechenninger** [comment]
Mkay, any of above options sound good to me. I think we only need latest document version, because we only want to run the update if that document version is still the latest.

I could see value in the shorthand version, even for updates too, since it is a common algorithm for concurrency control. But, either way works.

Maybe we can just always include this single latest doc version in response? Might be a little simpler than having a flag, but just a thought.

**Comment by bserdar** [comment]
Yes, I was thinking the same think regarding including doc version in
response by default. The problem with that is that it is not in metadata,
and if the client is not prepared to receive it, it may cause problems.
Maybe I can even return it as a separate array.

Maybe we can make version like _id, so it is a legitimate field?

Maybe we can add a documentInfo[] field in the response, and return
document hidden fields that could be useful?

Maybe we can add a __documentData field in the document, and put all such
"useful" fields there?

**Comment by paterczm** [comment]
I don't think adding docver to the response will cause problems on the client side, especially if it's not part of data object. I like the onlyIfVersion solution, as it does not require all clients updating given entity to support it (locking does).

**Comment by bserdar** [comment]
https://github.com/lightblue-platform/lightblue-core/pull/761
https://github.com/lightblue-platform/lightblue-mongo/pull/344
https://github.com/lightblue-platform/lightblue-client/pull/332
